language: node_js
node_js:
  - "10"
  - "8"
  - "6"
before_install:
  - 'nvm install-latest-npm'
services:
  - xvfb
before_script:
  - 'if [ -n "${KARMA-}" ]; then export DISPLAY=:99.0; fi'
script:
  - 'if [ -n "${LINT-}" ]; then npm run lint ; fi'
  - 'if [ -n "${BUILD-}" ]; then npm run build ; fi'
  - 'if [ "${TEST-}" = true ]; then npm run tests-only ; fi'
  - 'if [ -n "${KARMA-}" ]; then npm run tests-karma ; fi'
  - 'if [ -n "${COVERAGE-}" ] && [ "${TRAVIS_BRANCH-}" = "master" ]; then npm run cover; cat ./coverage/lcov.info | ./node_modules/.bin/coveralls ; fi'
  - 'if [ -n "${HAPPO-}" ]; then npm install --no-save happo-plugin-puppeteer && INSTALL_CMD="npm install && npm install --no-save happo-plugin-puppeteer" npm run happo-ci ; fi'
env:
  global:
    - TEST=true
    - secure: "lv5bnKRHd3A0tUequn7CrpKLkaZjVc1YmY/MzvX53wjqIwP4llpIil9XqeVYoG/VDGcf810XktZe2QeAuFUTXIZhPGQRXcWsbKbHVNmKSFQFDtXqEpB9NGw4NBCytK2ZLVXhRfrIcHm6Ltr0CSa+mO/KHtk9bE/on/Itjc0aB5b7Y1gVVHTfyZ3QOjIsPUenLRsY1tn1rUJ0meFlogPFIBbcnK+GPDL2oHsiVIOjCfBauIcRlNP7XZggFhZbHARZG7bTDr+YBuybAIBCVnex5Av7ho5EHu8FTjNrGXZyKF5IOMjqJla8UvOAoEnNe5k98O+Wx9ehlObUYGcr9szV9zGHvp0Wo+sflHdWYy5IOQAp+AQqjIz8J18ia6q0Zm9TBL5h2OEx/XwKzp4Q+F0XeTL7USnsfLuVdRBfEi4fOq/ucXnmOOJNJnBl8Q1IW5NYwF0nL1sW2jNVnQsp6a0sjLs0QWHEs1J0OMyru0vsWCJfkFQn1ozla62EzKClNW0dAvRJcHsOCD2JWCzToM3HysghPkT1jAZvfrW1ndBDYCipetgSx9AoYb2jYxrxFx3BoZBd23zIy5WDa0V/HkwijV04GEt0/V/rXF3pQzEaKE07sY8rjeTHNew/bmmNcid3/MsPv/8596j6ir4QmuxaHi/kP5ZTQWjtjytUADB7HqU=" # HAPPO_API_KEY
    - secure: "D/Rb+Ly1sekp86LkDObtRObkwSXCsq9OOLlIw8qEMUI3dijWx00eWCJLyVzi80gy6jGprSL2CljhmaeijB0/3gAY3bYxLblE1rY3qFWJJz6Z8GjnndbFJqoyhtGqy5wiZ3rq1W/7FPRTTuDj3ms8+z7kBPt9Ebo9AyTQN/53qC8KG3oMAECbkA30HSxkJyN6W9xmDE6JMMkQX8C/z0RwB5oksmnmX24TrmJOg13CFGmcC5OuIaFNjiOkTSPy7/5SVZScciZnPekgVlZiOvFfo2JnspXGNcUzpQ6PzfjEEaTrRTPt+tqtLSAtDKFvtZG711YlP1vBVUiV2D6YHgUCzwKYemtHm9b1bjuwkIcUNeQ0YuecnK+h4Qbkblf50vcYFhjaZrKgQVUbLhu1a20oaKRt2PYFZH4+f1xkFrWkgqWJQ2G//myRclDtdj65ofA7aH50BSc8z6gSfa6081DI/FEnGjTUjFSbR/5mToE6q8GkN4eo48Fnq91F0QwOqEWZ5z8I9cbHDLAlw9D6FM811T6lW2fKTRjaXvJNbiWBVm8LNQeFdyZoRPPHjhZ+ddKCCY9ZCjZLco0keCcvPo3j72bnNenTQ0I4l1H/IROhA3H8j16eUHmmgzKqlZkJOHNRJpzTpObu6mrmw6FP0yXSV/dmJqUN2WslB0QLaiR4JRw=" # HAPPO_API_SECRET
  matrix:
    - REACT=0.14
    - REACT=15
    - REACT=16
sudo: false
matrix:
  fast_finish: true
  include:
    - node_js: "lts/*"
      env: LINT=true TEST=false
    - node_js: "lts/*"
      env: BUILD=true TEST=false
    - node_js: "lts/*"
      env: COVERAGE=true TEST=false
    - node_js: "lts/*"
      env: KARMA=true TEST=false
    - node_js: "lts/*"
      env: HAPPO=true TEST=false
